"""empty message

Revision ID: 1388006e31c8
Revises: 8f7c511f5517
Create Date: 2020-04-13 20:51:00.184854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1388006e31c8'
down_revision = '8f7c511f5517'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('type', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment', 'type')
    # ### end Alembic commands ###
